### PR TITLE
Added silent expanse, Rymek, Corkus and some other gaps in Wynn and e…

### PR DESCRIPTION
**Pull request by JamieCallan117**
…dges of the map

### CODE REVIEW

**Comment by obj-obj** [comment]
No, you did that correctly

**Comment by JamieCallan117** [comment]
I think I forgot to actually update my local repo with some of the files, pushing new one now

**Comment by obj-obj** [comment]
Hmm, I see a potential issue here - since you didn't clone the repo before exploring more, some LODs got removed (probably from near the ocean)

It doesn't really matter for this PR since I can just spend 2 minutes going to those couple areas again but I should put that in the wiki for the future

**Comment by obj-obj** [comment]
Either that, or distant horizons is just being weird and there won't actually any chunks gone

**Comment by JamieCallan117** [comment]
I'm pretty sure I did clone it as almost all of the Wynn plains were done when I started doing other areas?

If you get the files I sent on Reddit and if those work then add them to the main branch and I'll clone again as I think I've screwed my fork up

**Pull request closed without merging**
