### PR TITLE
DH 2.0 LODs

### PR DESCRIPTION
**Pull request by MenacingPerson**
I'd say 21% of the important stuff is done. (Actual progress 4.4%) Not ready to merge yet.

Also, when merging, the wiki needs to be updated:

LOD Status page:
- Removed completely

Install/Setup:
- Must go directly into Wynncraft folder instead of dim_overworld or whatever
- "Multiplayer: Change Server Folder Mode to Name Only"
  - This isn't necessary anymore

(Please squash when merging)

### CODE REVIEW

**Comment by MenacingPerson** [comment]
Corkus
Corkus

**Comment by JamieCallan117** [comment]
Not sure if you have but remember to redo the molten heights, sky islands and silent expanse once 2.0.4 is out (or use the beta) as those will have new changes.

The upped render distance will be nice for this too, should make things a little bit faster

**Comment by MenacingPerson** [comment]
Okay I will have to redo SE

I also am a bit caught up and hence haven't been able to make any progress on this... I guess I'm free today, though, so I'll do this

**Comment by JamieCallan117** [comment]
I might do some then, what version of DH are you using, one of the release candidates or did you build it from the repo?

**Comment by MenacingPerson** [comment]
They have builds for the very latest commit in their discord

Direct link for 1.19.4 which auto-updates to the latest one: https://gitlab.com/jeseibel/minecraft-lod-mod/-/jobs/artifacts/main/download?job=build:%20[1.19.4]

**Comment by MenacingPerson** [comment]
I'm gonna boat around the ocean, that shouldn't have gotten any updates, you can push changes to this branch (if you have perms, not sure) and I'll merge them

**Comment by JamieCallan117** [comment]
Actually it might just be worth waiting for 2.0.4 so you can do it as don't want me to push some 2.0.4 changes and you accidently overwrite them

**Comment by MenacingPerson** [comment]
If one of our changes conflict I will prefer yours.. But yeah, best wait for 2.0.4

**Comment by obj-obj** [comment]
> They have builds for the very latest commit in their discord
> 
> Direct link for 1.19.4 which auto-updates to the latest one: [https://gitlab.com/jeseibel/minecraft-lod-mod/-/jobs/artifacts/main/download?job=build:%20[1.19.4]](https://gitlab.com/jeseibel/minecraft-lod-mod/-/jobs/artifacts/main/download?job=build:%20%5B1.19.4%5D)

Oh there's a CI build? I was compiling it manually...

**Comment by obj-obj** [comment]
> I'm gonna boat around the ocean, that shouldn't have gotten any updates, you can push changes to this branch (if you have perms, not sure) and I'll fix the conflicts

Make sure you're using bedrockify & bedrockwaters

**Comment by obj-obj** [comment]
> If one of our changes conflict I will prefer yours.. But yeah, best wait for 2.0.4

They probably will because git can't diff the compressed LOD files

**Comment by MenacingPerson** [comment]
> Make sure you're using bedrockify & bedrockwaters

Why? Is that necessary now in 2.0? Crap, didn't know

Time to redo a lot of LODS

**Comment by MenacingPerson** [comment]
Also, Wynntils updated to 1.20.2 but DH is stuck on 1.20.1, this situation sucks

**Comment by obj-obj** [comment]
> > Make sure you're using bedrockify & bedrockwaters
> 
> Why? Is that still necessary now in 2.0? Crap, didn't know
> 
> Time to redo a lot of LODs

It's not as necessary because 2.0 has that random noise feature, but just do all LODs with those mods from now don't (don't spend a bunch of time redoing the previous ones)

**Comment by MenacingPerson** [comment]
DH added 1.20.2, I will proceed with more lods tomorrow or the day after

**Comment by MenacingPerson** [comment]
Wait, Bedrockify and Bedrock Waters aren't on 1.20.2, :facepalm:

**Comment by MenacingPerson** [comment]
It seems DH will move to a sqlite database file for LODs. Not sure how good this is for us.

**Comment by obj-obj** [comment]
> It seems DH will move to a sqlite database file for LODs. Not sure how good this is for us.

Bad because before we could at least diff individual files, now we can't diff anything

**Comment by MenacingPerson** [comment]
Maybe we can bug them for a toggle?

**Comment by MenacingPerson** [comment]
We are so fucked
image

**Comment by obj-obj** [comment]
It's fine, we'll just have to do it without being able to diff the files (which means only one person could work on LODs at a time).

**Comment by obj-obj** [comment]
It might be worth making a new repo or branch, actually, as some people might still be using Distant Horizons 1.0.

**Comment by MenacingPerson** [comment]
These LODs are useless now, they aren't gonna make a converter

Unless someone else does

**Comment by obj-obj** [comment]
There might be another solution — I saw them working on the ability for the server to send LOD data to the client. Maybe we could campaign for Wynncraft to implement that?

**Comment by MenacingPerson** [comment]
What about the 2 year interim period before they implement that? (just kidding)

I mean, that'll be interesting, but we have to see if wynn even implements that

**Comment by MenacingPerson** [comment]
Time to redo this, SQLite style

**Comment by coolGi2007** [comment]
Ik this is a bit late, but someone on our Discord has made a conversion tool for the old format to sqlite, may help with the transition if you haven't already done it.\
https://github.com/gabmontes/dh-lod-to-sqlite

**Comment by MenacingPerson** [comment]
Oh, cool! Thanks for mentioning that.

Actually I think redoing it after 2.0 release might be better... No telling what changes in between.

@obj-obj BedrockWaters isn't on 1.20.2 yet. Does the 1.20.1 version work?

> > Bedrock Edition world color noise for grass and water.

I wonder how 2.0 LODs interact with that. I do feel it's a bit opinionated, and with 2.0 water transparency it becomes kind of irrelevant?

> Exporting the SQL data probably isn't a good idea because it would make this repo even less accessible for normies (although maybe we could recombine them using GitHub Actions and tell them to download the resulting file).

I think the GH actions idea would make it easier than it is, even currently. That's an upside for sure.

> It might be worth making a new repo or branch, actually, as some people might still be using Distant Horizons 1.0.

DH is multi-version. There's no reason to support 1.0 imo.


Gonna try doing LODs again.

**Comment by obj-obj** [comment]
> Oh, cool! Thanks for mentioning that.
> 
> Actually I think redoing it after 2.0 release might be better... No telling what changes in between.
> 
> @obj-obj BedrockWaters isn't on 1.20.2 yet. Does the 1.20.1 version work?
> 
> > > Bedrock Edition world color noise for grass and water.
> 
> I wonder how 2.0 LODs interact with that. I do feel it's a bit opinionated, and with 2.0 water transparency it becomes kind of irrelevant?
> 
> > Exporting the SQL data probably isn't a good idea because it would make this repo even less accessible for normies (although maybe we could recombine them using GitHub Actions and tell them to download the resulting file).
> 
> I think the GH actions idea would make it easier than it is, even currently. That's an upside for sure.
> 
> > It might be worth making a new repo or branch, actually, as some people might still be using Distant Horizons 1.0.
> 
> DH is multi-version. There's no reason to support 1.0 imo.
> 
> Gonna try doing LODs again.

Yeah, I think it becomes irrelevant with the water transparency and random noise texture, although it would still look a bit better.

As for the exporting idea, it'd also be annoying to keep manually exporting the data, but I'll see if I can work something out after I'm done with college apps.

I should also probably make a Matrix room, so we don't have to keep talking in PRs and issues. I'll make one and put it in the README right now.

**Pull request closed without merging**
