### PR TITLE
Added some chunks found whilst exploring

### PR DESCRIPTION
**Pull request by Coow**

### CODE REVIEW

**Comment by obj-obj** [comment]
@Coow did you clone this repository before exploring?

**Comment by obj-obj** [comment]
Actually I'll just test it

**Comment by Coow** [comment]
Sorry, didn't get a notification. Yes. I pulled the latest before making the PR :)

**Comment by obj-obj** [comment]
> Sorry, didn't get a notification. Yes. I pulled the latest before making the PR :)

Its fine it just took me like 2 mins to check it ingame

**Pull request merged**
