### PR TITLE
2.0 LODs 2.0.4

### PR DESCRIPTION
**Pull request by JamieCallan117**
Done on this nightly build https://gitlab.com/jeseibel/minecraft-lod-mod/-/jobs/5236970009

Will obviously be outdated once they change to using sql for storage but I was collecting some npc locations for Wynntils and thought may as well do this at the same time. So enjoy this while it lasts

Water is a bit funny on this build but I think I got 99% of the main map

### CODE REVIEW

**Comment by MenacingPerson** [comment]
They already changed to sql for storage

**Comment by MenacingPerson** [comment]
How did you take this screenshot btw?

**Comment by JamieCallan117** [comment]
> They already changed to sql for storage

Well that lasted long.

I see you've already said on the Wynntils Discord you'll do the whole map so hopefully you'll pick up some I missed whilst doing this again

**Comment by JamieCallan117** [comment]
> How did you take this screenshot btw?
> 

https://modrinth.com/mod/freecam

Useful for spotting chunks you've missed too

**Comment by MenacingPerson** [comment]
I am sadly not going to be able to do LODs. Someone else needs to. Sorry!

**Comment by JamieCallan117** [comment]
> I am sadly not going to be able to do LODs. Someone else needs to. Sorry!

No worries, if I find an hour or two with nothing to do I'll go over it all again

**Comment by JamieCallan117** [comment]
Final release candidate is out for 2.0 so probably worth waiting for that before doing a remap

**Pull request closed without merging**
